version: '3'
services:   
  database:      
    image: mongo:4.4.12      
    ports:         
      - 27017:27017        
  auth:      
    image: auth:v1
    restart: always  
    ports: 
      - 80:5000        
    depends_on:           
      - database

  

 