version: '3'
services:   
  database:      
    image: mongo:4.4.12      
    ports:         
      - 27017:27017
    volumes:
    - databaseVolume:/data/db/          
  goApp:      
    image: auth:v1
    restart: always  
    ports: 
      - 80:9000        
    depends_on:           
      - database 
volumes:
    databaseVolume:  

 