version: '3'
services:   
  database:      
    image: mongo:4.4.12      
    ports:         
      - 27017:27017
    volumes:
    - :data/db          
  goApp:      
    image: auth:v1
    restart: always  
    ports: 
      - 80:9000        
    depends_on:           
      - database
  feims:
    image: ujere/lexington:feims
    volumes: 
      - :/app
    depends_on: 
      - database
    ports: 
      - "5500:5500"
  

 