version: '3'
services:   
  db:      
    image: mongo      
    ports:         
      - 27017:27017        
  web:      
    image: auth:v4   
    ports: 
      - 5000:5000        
    depends_on:           
      - db
  

 