version: '3'
services:   
  mongo:      
    image: mongo:latest      
    ports:         
      - 27017:27017        
  web:      
    image: auth:v5   
    ports: 
      - 80:5000        
    depends_on:           
      - mongo
  

 