version: '3'
services:   
  mongo:      
    image: mongo:4.4.12      
    ports:         
      - 27017:27017        
  auth:      
    image: auth:v3 
    restart: always  
    ports: 
      - 5000:5000        
    depends_on:           
      - mongo
  forms:
    image: forms:v4
    restart: always
    ports:
      - 3000:3000
    depends_on:           
      - mongo

 