version: '3'
services:
  auth:
    restart: always
    image: auth:v4
    ports:
      - 5000:5000
    depends_on:
      - mongo
    network_mode: bridge  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    network_mode: bridge  
  

 