version: '3'
services:   
  mongo:      
    image: mongo:latest      
    ports:         
      - 27017:27017        
  web:      
    image: auth:v2 
    restart: always  
    ports: 
      - 80:5000        
    depends_on:           
      - mongo
  form:      
    image: form:v2 
    restart: always  
    ports: 
      - 3000:3000        
    depends_on:           
      - mongo
  

 